apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-metaflow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-metaflow
  template:
    metadata:
      labels:
        app: fastapi-metaflow
    spec:
      containers:
        - name: fastapi-metaflow-container
          image: fastapi-metaflow-image:latest
          imagePullPolicy: Never  # Use local image
          ports:
            - containerPort: 8000
          env:
            - name: USERNAME
              value: "fastapi-user"
            - name: METAFLOW_S3_DATATOOLS_PREFIX
              value: "s3://metaflow-test"
            - name: METAFLOW_S3_DATATOOLS_ENDPOINT_URL
              value: "http://metaflow-s3.metaflow-dev.svc.cluster.local:9000"
            - name: METAFLOW_S3_DATATOOLS_ACCESS_KEY_ID
              value: "minio"
            - name: METAFLOW_S3_DATATOOLS_SECRET_ACCESS_KEY
              value: "minio123"