apiVersion: v1
kind: Service
metadata:
  name: fastapi-metaflow-service
spec:
  selector:
    app: fastapi-metaflow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer # Expose the service outside the cluster