# Deployment: for stateless applications
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${app_name}
  namespace: ${namespace_name}
  labels:
    app: ${app_name}
# spec is the desired state which gets reconciled by controller.
# If there are too few Pods, it creates more.
# If there are too many, it removes extras.
# If Pods are unhealthy, it replaces them.
spec:
  replicas: ${replica_count}
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 1200
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels: # so service.yaml matches this deployment.yaml
      app: ${app_name}
  template:
    metadata:
      labels:
        app: ${app_name}
      annotations:
        kubectl.kubernetes.io/restartedAt: ${rollout_trigger}
    spec:
%{ if is_local_deployment == false }
      imagePullSecrets:
        - name: ${image_pull_secret_name}
%{ endif }
      containers:
        - name: ${app_name}
          image: ${image_name}:${image_tag}
%{ if is_local_deployment == true }
          imagePullPolicy: Never
%{ else }
          imagePullPolicy: Always
%{ endif }
          ports:
            - containerPort: ${target_port}
%{ if has_probing == true }
          livenessProbe:
            httpGet:
              path: /livez
              port: ${target_port}
            initialDelaySeconds: 60
            periodSeconds: 1200 # how often to probe in seconds
            timeoutSeconds: 3 # how many seconds can request be
            failureThreshold: 3 # consecutive failures before action
          readinessProbe:
            httpGet:
              path: /readyz
              port: ${target_port}
            initialDelaySeconds: 30
            periodSeconds: 300 # how often to probe in seconds
            successThreshold: 3 # must succeed 3 times
            failureThreshold: 2 # consecutive failures before action
%{ endif }
          resources:
            requests:
              cpu: ${request_cpu} # e.g. "128m"
              memory: ${request_memory} # e.g. "256Mi"
            limits:
              cpu: ${limit_cpu} # e.g. "256m"
              memory: ${limit_memory} # e.g. "1Gi"
