apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ${project_namespace_name}-gateway
  namespace: ${project_namespace_name}
spec:
  gatewayClassName: nginx
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: ${ingress_host}
      allowedRoutes:
        namespaces:
          from: All
