apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${app_name}-route
  namespace: ${namespace_name}
spec:
  parentRefs:
    - name: ${namespace_name}-gateway
      namespace: ${gateway_namespace}
  hostnames:
    - ${ingress_host}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: ${ingress_path}
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: ${app_name}-svc
          port: 80
