apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hera-submitter-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hera-submitter-role # The custom role you created
subjects:
- kind: ServiceAccount
  name: hera-submitter
  namespace: argo # The namespace where the ServiceAccount lives