apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-storage # TODO: templatize
provisioner: rancher.io/local-path # TODO: templatize, A common provisioner in local environments like kind
reclaimPolicy: Delete # TODO: templatize
volumeBindingMode: Immediate